import assert from 'node:assert/strict';
import { StateStore } from '../src/engine/state.js';
import { extractDesignRules } from '../src/engine/design_rules.js';
import { registerDesignRulesTools } from '../src/mcp/design_rules_tools.js';

globalThis.localStorage = {getItem:()=>null,setItem:()=>{},removeItem:()=>{}};
globalThis.window = {devicePixelRatio:1};
const layer = {id:'design',type:'rect',x:0,y:0,width:100,height:100,visible:true,fill:'#ffffff'};
const makeStore = () => new StateStore({title:'Rules integration',layers:[structuredClone(layer)],viewport:{panX:0,panY:0,zoom:1}});
const snapshot = store => JSON.stringify({state:store.state,undo:store.undoStack,redo:store.redoStack});
const store = makeStore();
const registry = new Map();
registerDesignRulesTools(store,{registerTool:spec=>registry.set(spec.name,spec)});
const invoke = (name,args = {}) => registry.get(name).execute(args);

const beforeProposal = snapshot(store);
const proposal = await invoke('figma_extract_design_rules');
assert.equal(proposal.status,'proposal');
assert.equal(snapshot(store),beforeProposal,'Extracting a proposal must never activate or mutate');
assert.equal(store.state.designContract,undefined);
await assert.rejects(()=>invoke('figma_preview_changes',{updates:[{id:'design',properties:{x:10}}]}),/contrato/);
store.activateDesignContract(proposal.contract);
assert.equal(store.state.designContract.status,'active');
const accepted = snapshot(store);
assert.throws(()=>store.updateLayer('design',{fill:'#000000'}),/contrato/);
assert.equal(snapshot(store),accepted,'Rejected update restores exact state and history');
store.state.layers[0].fill = '#000000';
assert.throws(()=>store.notify('direct-mutation'),/contrato/);
assert.equal(snapshot(store),accepted,'Generic mutation also rolls back');
assert.throws(()=>store.loadState({title:'Replacement',layers:[{...layer,fill:'#000000'}]}),/contrato/);
assert.equal(snapshot(store),accepted,'Invalid import cannot replace active project or contract');

const undoStore = makeStore();
undoStore.updateLayer('design',{fill:'#123456'});
undoStore.activateDesignContract(extractDesignRules(undoStore.state.layers));
const beforeUndo = snapshot(undoStore);
assert.throws(()=>undoStore.undo(),/contrato/);
assert.equal(snapshot(undoStore),beforeUndo,'Undo violating newly approved contract rolls back both stacks');

const invalid = await invoke('figma_preview_changes',{updates:[{id:'design',properties:{fill:'#000000'}}]});
assert.equal(invalid.valid,false);
assert.ok(invalid.violations.length);
assert.equal(invalid.confirmationToken,undefined);
assert.equal(snapshot(store),accepted,'Invalid preview is read-only');
const valid = await invoke('figma_preview_changes',{updates:[{id:'design',properties:{x:10}}]});
assert.equal(valid.valid,true);
assert.equal(snapshot(store),accepted,'Valid preview also does not mutate');
await invoke('figma_apply_validated_changes',{confirmationToken:valid.confirmationToken});
assert.equal(store.state.layers[0].x,10);
assert.equal(store.undoStack.length,1);
await assert.rejects(()=>invoke('figma_apply_validated_changes',{confirmationToken:valid.confirmationToken}),/Token/);

const stale = await invoke('figma_preview_changes',{updates:[{id:'design',properties:{x:20}}]});
store.setViewport(5,0,1);
const afterViewport = snapshot(store);
await assert.rejects(()=>invoke('figma_apply_validated_changes',{confirmationToken:stale.confirmationToken}),/cambió/);
assert.equal(snapshot(store),afterViewport,'Stale application never mutates');
await assert.rejects(()=>invoke('figma_preview_changes',{updates:[{id:'design',properties:{locked:false}}]}),/permitidas/);
await assert.rejects(()=>invoke('figma_preview_changes',{updates:[{id:'design',properties:{width:NaN}}]}),/finito/);
assert.equal((await invoke('figma_get_design_rules')).status,'active');
assert.equal((await invoke('figma_validate_design')).valid,true);
const exported = await invoke('figma_export_design_rules');
assert.equal(exported.status,'active');
assert.equal(typeof exported.content.designMd,'string');
assert.deepEqual(JSON.parse(exported.content.contractJson),store.state.designContract);
clearTimeout(store._saveTimeout);
clearTimeout(undoStore._saveTimeout);
const protectionStore = makeStore();
const protectionRegistry = new Map();
registerDesignRulesTools(protectionStore,{registerTool:spec=>protectionRegistry.set(spec.name,spec)});
const protectionCall = (name,args={}) => protectionRegistry.get(name).execute(args);
const prepareProtection = () => protectionCall('figma_prepare_design_protection');
const activateProtection = confirmationToken => protectionCall('figma_activate_design_rules',{confirmationToken});
const initialProtectionState = snapshot(protectionStore);
const staleProtection = await prepareProtection();
assert.equal(staleProtection.requiresUserAuthorization,true);
assert.equal(snapshot(protectionStore),initialProtectionState,'Preparing protection must never activate or mutate');
protectionStore.setViewport(1,2,1);
await assert.rejects(()=>activateProtection(staleProtection.confirmationToken),/cambió/);
assert.ok(!protectionStore.state.designContract);
const expiredProtection = await prepareProtection();
const realNow = Date.now;
const later = realNow()+60001;
Date.now = () => later;
try { await assert.rejects(()=>activateProtection(expiredProtection.confirmationToken),/caducada/); }
finally { Date.now = realNow; }
const supersededProtection = await prepareProtection();
const approvedProtection = await prepareProtection();
await assert.rejects(()=>activateProtection(supersededProtection.confirmationToken),/inválida/);
const activatedProtection = await activateProtection(approvedProtection.confirmationToken);
assert.equal(activatedProtection.status,'active');
assert.equal(protectionStore.state.designContract.status,'active');
assert.equal(protectionStore.persistenceStatus.status,'saved');
await assert.rejects(()=>activateProtection(approvedProtection.confirmationToken),/inválida/);
const afterProtection = snapshot(protectionStore);
await assert.rejects(()=>prepareProtection(),/activa/);
assert.equal(snapshot(protectionStore),afterProtection,'Active contract cannot be replaced through preparation');
assert.throws(()=>protectionStore.updateLayer('design',{fill:'#000000'}),/contrato/);
assert.equal(snapshot(protectionStore),afterProtection);
clearTimeout(protectionStore._saveTimeout);
const racedStore = makeStore();
const racedRegistry = new Map();
registerDesignRulesTools(racedStore,{registerTool:spec=>racedRegistry.set(spec.name,spec)});
const racedProposal = await racedRegistry.get('figma_prepare_design_protection').execute({});
racedStore.activateDesignContract(extractDesignRules(racedStore.state.layers));
const alreadyApproved = snapshot(racedStore);
await assert.rejects(()=>racedRegistry.get('figma_activate_design_rules').execute({confirmationToken:racedProposal.confirmationToken}),/cambió/);
assert.equal(snapshot(racedStore),alreadyApproved,'Approval after preparation cannot be replaced by token activation');
clearTimeout(racedStore._saveTimeout);
console.log('Design rules integration: central rollback, import/undo guard, pure previews and validated application passed');
